import * as SDK from '../../core/sdk/sdk.js';
import * as Workspace from '../workspace/workspace.js';
import type { DebuggerSourceMapping, DebuggerWorkspaceBinding } from './DebuggerWorkspaceBinding.js';
export declare class CompilerScriptMapping implements DebuggerSourceMapping {
    private readonly debuggerModel;
    private readonly sourceMapManager;
    private readonly workspace;
    private readonly debuggerWorkspaceBinding;
    private readonly regularProject;
    private readonly contentScriptsProject;
    private readonly regularBindings;
    private readonly contentScriptsBindings;
    private readonly stubUISourceCodes;
    private readonly stubProject;
    private readonly eventListeners;
    constructor(debuggerModel: SDK.DebuggerModel.DebuggerModel, workspace: Workspace.Workspace.WorkspaceImpl, debuggerWorkspaceBinding: DebuggerWorkspaceBinding);
    private onUiSourceCodeAdded;
    private addStubUISourceCode;
    private removeStubUISourceCode;
    static uiSourceCodeOrigin(uiSourceCode: Workspace.UISourceCode.UISourceCode): string[];
    mapsToSourceCode(rawLocation: SDK.DebuggerModel.Location): boolean;
    uiSourceCodeForURL(url: string, isContentScript: boolean): Workspace.UISourceCode.UISourceCode | null;
    rawLocationToUILocation(rawLocation: SDK.DebuggerModel.Location): Workspace.UISourceCode.UILocation | null;
    uiLocationToRawLocations(uiSourceCode: Workspace.UISourceCode.UISourceCode, lineNumber: number, columnNumber: number): SDK.DebuggerModel.Location[];
    private sourceMapWillAttach;
    private sourceMapFailedToAttach;
    private sourceMapAttached;
    private sourceMapDetached;
    sourceMapForScript(script: SDK.Script.Script): SDK.SourceMap.SourceMap | null;
    scriptsForUISourceCode(uiSourceCode: Workspace.UISourceCode.UISourceCode): SDK.Script.Script[];
    private sourceMapAttachedForTest;
    private populateSourceMapSources;
    static uiLineHasMapping(uiSourceCode: Workspace.UISourceCode.UISourceCode, lineNumber: number): boolean;
    dispose(): void;
}
